Attempt to fix different compiler version
Attempt to fix "fatal error C1900: Il mismatch between 'P1' version '20250730' and 'P2' version '20240319'" error due to outdated MSVC compiler for NativeAOT transpiling. It's required to use VS2026 instead of VS2022 as it's still using MSVC 14 instead of MSVC 19 which expected to be used by the ILC.

For now, VS2026 is only available on windows server 2025 runner, which is currently under public beta.

Also removing unused branch from build.yml

@bagusnl let me know if something were missing.